---
- name: Create VM in template
  hosts: all
  vars:
    - vcenter_ip: 192.168.1.184
    - vcenter_username: administrator@server.ivt
    - vcenter_password: 'P@ssw0rd'
    - datacenter_name: DC-IVT
    - cluster_name: Cluster-IVT
  tasks:
    - name: Clone the template
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        name: "{{ hostname }}"
        template: RHEL8_TEMP
        datacenter: "{{ datacenter_name }}"
        folder: yosep
        disk:
        - size_gb: "{{ disk }}"
          type: thin
          datastore: SSD1
        hardware:
          memory_mb: "{{ memory }}"
          num_cpus: "{{ cpu }}"
          scsi: paravirtual
        networks:
         - name: VM Network
           ip: "{{ ip_address }}"
           netmask: 255.255.255.0
           gateway: 192.168.1.254
           domain: server.ivt
           dns_servers:
             - 192.168.1.170
           type: static
        customization:
          dns_servers:
          - 192.168.1.170
          domain: server.ivt
          password: new_vm_password
        state: poweredon
        cluster: "{{ cluster_name }}"
        wait_for_ip_address: yes
