---
- name: Create VM in template
  hosts: all
  vars:
    - vcenter_ip: 192.168.1.184
    - vcenter_username: administrator@server.ivt
    - vcenter_password: 'P@ssw0rd'
    - datacenter_name: DC-IVT
    - cluster_name: Cluster-IVT
  tasks:
    - name: Clone the template
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        name: testvm1
        template: RHEL8_TEMP
        datacenter: "{{ datacenter_name }}"
        folder: yosep
        state: poweredon
        cluster: "{{ cluster_name }}"
        wait_for_ip_address: yes
